# Generated by Django 3.1.6 on 2021-02-10 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20210210_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookfileupload',
            name='book_file',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.book'),
        ),
    ]
