# Generated by Django 3.1.6 on 2021-02-10 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20210210_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookfileupload',
            name='book_file',
        ),
    ]
