# Generated by Django 3.1.6 on 2021-02-10 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_remove_bookfileupload_book_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookFileUpload',
        ),
    ]
