# Generated by Django 3.1.6 on 2021-02-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_bookfileupload_book_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('unregistered', 'unregistered'), ('registered', 'registered')], max_length=20),
        ),
    ]
