# Generated by Django 3.1.6 on 2021-02-16 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_book_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookFileUpload',
        ),
    ]
